In [9]:
import pandas as pd

# Load and inspect the uploaded CSV file
df = pd.read_csv('data\percentage-of-population-exposed-to-5.csv')
df

,Country:text,55 - 59 dB:number,60 - 64 dB:number,65 - 69 dB:number,70 - 74 dB:number,greater than 75 dB:number,sum:number
0,Austria,21.33,14.44,8.11,1.94,0.13,45.95
1,Belgium,33.25,23.49,16.71,9.13,1.38,83.95
2,Bulgaria,22.21,34.39,21.13,5.36,0.38,83.47
3,Croatia,18.14,12.54,5.74,0.86,0.02,37.30
4,Cyprus,13.61,71.50,7.09,5.18,0.39,97.78
5,Czech Republic,33.45,20.72,11.44,5.82,0.44,71.86
6,Denmark,23.70,15.71,11.22,5.72,0.25,56.60
7,Estonia,18.09,22.82,15.30,4.73,0.29,61.23
8,Finland,17.38,13.78,6.51,2.02,0.07,39.75
9,France,10.61,10.22,7.90,3.29,0.57,32.59
10,Germany,10.39,6.77,4.78,2.06,0.27,24.27
11,Hungary,12.41,13.29,12.18,2.99,0.11,40.98
12,Ireland,25.04,12.13,10.64,6.69,0.95,55.44
13,Italy,14.83,19.83,16.74,11.12,3.79,66.31
14,Latvia,20.31,28.65,21.82,8.25,0.76,79.78
15,Lithuania,26.41,22.45,13.93,4.22,0.50,67.52
16,Luxembourg,28.74,26.20,14.03,5.67,0.07,74.72
17,Malta,6.04,4.59,5.22,1.85,0.33,18.04
18,Netherlands,17.63,13.94,6.32,0.53,0.00,38.42
19,Poland,20.72,16.54,11.10,5.00,0.92,54.27
20,Portugal,15.40,13.62,9.64,2.50,0.22,41.37
21,Romania,11.21,17.39,15.99,5.54,1.64,51.76
22,Slovakia,21.53,15.75,8.74,2.67,1.11,49.80
23,Slovenia,19.84,17.95,14.28,2.90,0.03,54.99
24,Spain,18.96,22.22,17.08,8.64,1.40,68.30
25,Sweden,19.15,9.92,5.37,1.18,0.19,35.81
26,United Kingdom,11.74,5.08,4.28,3.00,0.40,24.50
27,EU-28,14.78,12.45,8.92,4.18,0.76,41.08

In [ ]:
# Display the first few rows and the basic information about the data
data_info = data.info()
data_head = data.head()

data_info, data_head